"""d3-format parity tests against real d3.js output.

The fixture was generated by running d3-format (npm) over a matrix of
(spec, value) pairs. Every entry here must match byte-for-byte.

TDD: these tests are written BEFORE the implementation.
"""

import json
import math
import pathlib

import pytest

from d3_format import format as d3_format

FIXTURE = json.loads(
    (pathlib.Path(__file__).parent / "fixtures" / "d3_reference.json").read_text()
)

_SPECIAL_VALUE_MAP: dict[str, float] = {
    "NaN": math.nan,
    "Infinity": math.inf,
    "-Infinity": -math.inf,
    "-0": float("-0"),
}


def _parse_value(label: str) -> float:
    if label in _SPECIAL_VALUE_MAP:
        return _SPECIAL_VALUE_MAP[label]
    return float(label)


@pytest.mark.parametrize(
    ("spec", "value_label", "expected"),
    [(item["spec"], item["value"], item["expected"]) for item in FIXTURE],
    ids=[f"{item['spec']}({item['value']})" for item in FIXTURE],
)
def test_parity(spec: str, value_label: str, expected: str) -> None:
    value = _parse_value(value_label)
    result = d3_format(spec)(value)
    assert result == expected, (
        f"d3_format({spec!r})({value_label}) = {result!r}, expected {expected!r}"
    )
