"""Generated. Do not edit by hand — run `just generate-schema-names`.

Source: list_built_in_themes() (compile/config.py), PREDEFINED_SPECS
(text/predefined_formats.py), list_palettes() (compile/resolve/style/palette.py),
VEGA_SCHEME_NAMES (compile/models/primitives.py).
"""

from __future__ import annotations

from typing import Literal

# Built-in theme stems offered as `theme:`/`extends:` value completions.
# Excludes the private `_base` completeness floor and diagnostic-only themes.
ThemeName = Literal[
    "cream",
    "editorial",
    "neon",
    "plain",
    "solid",
    "stark",
    "vivid",
]

# Named dbt charts palettes (sequential, diverging, categorical, scaffold, tone).
# Excludes hard-fail anti-pattern names and warn-alias migration names — neither
# is a real palette YAML entry, so list_palettes() already omits them.
PaletteName = Literal[
    "category-6-tonal-blue",
    "category-6-tonal-brown",
    "category-6-tonal-green",
    "category-6-tonal-orange",
    "category-6-tonal-purple",
    "dbt-creams",
    "dbt-div-blue-red",
    "dbt-div-blue-red-dark",
    "dbt-div-coolwarm",
    "dbt-div-coolwarm-dark",
    "dbt-div-crimson-green",
    "dbt-div-crimson-green-dark",
    "dbt-div-orange-teal",
    "dbt-div-orange-teal-dark",
    "dbt-div-sunset",
    "dbt-div-sunset-dark",
    "dbt-grays",
    "dbt-seq-amber",
    "dbt-seq-amber-dark",
    "dbt-seq-blue",
    "dbt-seq-blue-dark",
    "dbt-seq-brown",
    "dbt-seq-brown-dark",
    "dbt-seq-gray",
    "dbt-seq-gray-dark",
    "dbt-seq-green",
    "dbt-seq-green-dark",
    "dbt-seq-purple",
    "dbt-seq-purple-dark",
    "dbt-seq-rust",
    "dbt-seq-rust-dark",
    "dbt-seq-teal",
    "dbt-seq-teal-dark",
    "editorial-10",
    "editorial-10-dark",
    "editorial-10-ghost",
    "editorial-10-ink",
    "editorial-10-light",
    "hero-6",
    "info",
    "negative",
    "positive",
    "tableau",
    "vivid-10",
    "vivid-10-dark",
    "vivid-10-ghost",
    "vivid-10-ink",
    "vivid-10-light",
    "warning",
]

# PaletteName union Vega/Vega-Lite scheme names — the only closed set
# ScaleTargetConfig.palette accepts (it also forwards Vega scheme names
# straight through to VL's scale.scheme). Hard-fail and warn-alias scheme
# names (e.g. 'rainbow') are excluded — see _HARD_FAIL_NAMES/_WARN_ALIASES.
ScalePaletteName = Literal[
    "accent",
    "bluegreen",
    "blueorange",
    "bluepurple",
    "blues",
    "brownbluegreen",
    "browns",
    "category-6-tonal-blue",
    "category-6-tonal-brown",
    "category-6-tonal-green",
    "category-6-tonal-orange",
    "category-6-tonal-purple",
    "category10",
    "category20",
    "category20b",
    "category20c",
    "cividis",
    "dark2",
    "darkblue",
    "darkgold",
    "darkgreen",
    "darkmulti",
    "darkred",
    "dbt-creams",
    "dbt-div-blue-red",
    "dbt-div-blue-red-dark",
    "dbt-div-coolwarm",
    "dbt-div-coolwarm-dark",
    "dbt-div-crimson-green",
    "dbt-div-crimson-green-dark",
    "dbt-div-orange-teal",
    "dbt-div-orange-teal-dark",
    "dbt-div-sunset",
    "dbt-div-sunset-dark",
    "dbt-grays",
    "dbt-seq-amber",
    "dbt-seq-amber-dark",
    "dbt-seq-blue",
    "dbt-seq-blue-dark",
    "dbt-seq-brown",
    "dbt-seq-brown-dark",
    "dbt-seq-gray",
    "dbt-seq-gray-dark",
    "dbt-seq-green",
    "dbt-seq-green-dark",
    "dbt-seq-purple",
    "dbt-seq-purple-dark",
    "dbt-seq-rust",
    "dbt-seq-rust-dark",
    "dbt-seq-teal",
    "dbt-seq-teal-dark",
    "editorial-10",
    "editorial-10-dark",
    "editorial-10-ghost",
    "editorial-10-ink",
    "editorial-10-light",
    "goldgreen",
    "goldorange",
    "goldred",
    "greenblue",
    "greens",
    "greys",
    "hero-6",
    "inferno",
    "info",
    "lightgreyred",
    "lightgreyteal",
    "lightmulti",
    "lightorange",
    "lighttealblue",
    "magma",
    "negative",
    "observable10",
    "orangered",
    "oranges",
    "paired",
    "pastel1",
    "pastel2",
    "pinkyellowgreen",
    "plasma",
    "positive",
    "purpleblue",
    "purplebluegreen",
    "purplegreen",
    "purpleorange",
    "purplered",
    "purples",
    "redblue",
    "redgrey",
    "redpurple",
    "reds",
    "redyellowblue",
    "redyellowgreen",
    "set1",
    "set2",
    "set3",
    "sinebow",
    "spectral",
    "tableau",
    "tableau10",
    "tableau20",
    "tealblues",
    "teals",
    "turbo",
    "viridis",
    "vivid-10",
    "vivid-10-dark",
    "vivid-10-ghost",
    "vivid-10-ink",
    "vivid-10-light",
    "warmgreys",
    "warning",
    "yellowgreen",
    "yellowgreenblue",
    "yelloworangebrown",
    "yelloworangered",
]

# Engine-predefined format names (PredefinedNumberFormat + PredefinedTimeFormat).
# A predefined name resolves to a d3 spec or native formatter at render time;
# a raw d3 spec or user style.formats alias is equally legal, so every field
# carrying this reads `FormatAlias | str` — the Literal names the shortcuts,
# it does not close the set.
FormatAlias = Literal[
    "compact",
    "currency",
    "currency_compact",
    "currency_whole",
    "date_short",
    "delta",
    "integer",
    "number",
    "number_default",
    "percent",
    "percent_delta",
    "percent_whole",
    "year",
]
