"""TextMate grammar renderer — generates dbt-charts.tmLanguage.json from a HighlightManifest.

The grammar is entirely self-contained (no template file). All dbt-charts-specific
patterns (top-level keys, enum values) come from the manifest; SQL/Jinja/YAML
boilerplate is defined here in Python.

Entry point: ``render_textmate_grammar(manifest: HighlightManifest) -> dict``
"""

from __future__ import annotations

from dbt_charts.core.compile.schema.renderers.highlight_manifest import (
    HighlightManifest,
)

_SCHEMA_URL = (
    "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json"
)

# Scope names for known highlighting enum keys.  Keys not listed here raise
# ValueError — add them here rather than adding a silent fallback default.
_ENUM_SCOPE_NAMES: dict[str, str] = {
    "type": "constant.language.chart-type.dbt-charts",
    "input": "constant.language.input-type.dbt-charts",
}


def _top_level_keys_pattern(keys: list[str]) -> dict[str, object]:
    alternation = "|".join(sorted(keys))
    return {
        "comment": "Top-level section keys - use cyan/type color",
        "patterns": [
            {
                "match": f"^({alternation})(:)",
                "captures": {
                    "1": {"name": "support.type.property-name.yaml"},
                    "2": {"name": "punctuation.separator.key-value.yaml"},
                },
            }
        ],
    }


def _enum_values_patterns(
    enum_values_by_key: dict[str, list[str]],
) -> dict[str, object]:
    patterns: list[dict[str, object]] = []
    for key in sorted(enum_values_by_key):
        if key not in _ENUM_SCOPE_NAMES:
            raise ValueError(
                f"No scope name defined for highlight enum key {key!r}; "
                "add it to _ENUM_SCOPE_NAMES in textmate_grammar.py"
            )
        alternation = "|".join(sorted(enum_values_by_key[key]))
        patterns.append(
            {
                "match": f"(?<={key}:\\s*)({alternation})\\b",
                "name": _ENUM_SCOPE_NAMES[key],
            }
        )
    return {
        "comment": "Known enum values like chart types, input types - use constant color",
        "patterns": patterns,
    }


def _sql_block_pattern(sql_keys: list[str]) -> dict[str, object]:
    alternation = "|".join(sorted(sql_keys))
    return {
        "comment": (
            "SQL block with embedded highlighting"
            " - ends when we see a YAML key at 0-4 space indent"
        ),
        "contentName": "meta.embedded.block.sql.dbt-charts",
        "begin": f"^(\\s*)({alternation})(:)\\s*(\\|[-+]?|>[-+]?)\\s*$",
        "beginCaptures": {
            "2": {"name": "support.type.property-name.yaml"},
            "3": {"name": "punctuation.separator.key-value.yaml"},
            "4": {"name": "punctuation.definition.block.scalar.yaml"},
        },
        "end": "^(?=[ ]{0,4}[a-zA-Z_][a-zA-Z0-9_-]*:)",
        "patterns": [
            {"include": "#jinja-template"},
            {"include": "#sql-content"},
        ],
    }


def render_textmate_grammar(manifest: HighlightManifest) -> dict[str, object]:
    """Generate the complete dbt-charts.tmLanguage.json dict from a HighlightManifest.

    Args:
        manifest: Highlight manifest produced by ``render_highlight_manifest()``.

    Returns:
        Dict suitable for ``json.dumps`` as the tmLanguage grammar file.
    """
    return {
        "$schema": _SCHEMA_URL,
        "name": "dbt charts Board",
        "scopeName": "source.dbt-charts",
        "fileTypes": ["dbt_charts.yml", "dbt_charts.yaml"],
        "_comment": "Generated by: just gen-highlight-artifacts — do not edit by hand",
        "patterns": [
            {"include": "#comment"},
            {"include": "#document-marker"},
            {"include": "#node"},
        ],
        "repository": {
            "comment": {
                "patterns": [
                    {
                        "name": "comment.line.number-sign.yaml",
                        "match": "#.*$",
                    }
                ]
            },
            "document-marker": {
                "patterns": [
                    {
                        "name": "entity.other.document.begin.yaml",
                        "match": "^---",
                    },
                    {
                        "name": "entity.other.document.end.yaml",
                        "match": "^\\.\\.\\.",
                    },
                ]
            },
            "node": {
                "comment": (
                    "Jinja outranks flow-collection: both begin at `{`, and a tie"
                    " on position is broken by order, so #flow-mapping would"
                    " otherwise swallow the `{` of an unquoted `title: Foo{% if"
                    " x %}` and leave the rest unscoped"
                ),
                "patterns": [
                    {"include": "#block-mapping"},
                    {"include": "#block-sequence"},
                    {"include": "#jinja-template"},
                    {"include": "#flow-collection"},
                    {"include": "#scalar"},
                ],
            },
            "block-mapping": {
                "patterns": [
                    {"include": "#dbt-charts-top-level-keys"},
                    {"include": "#dbt-charts-definition-names"},
                    {"include": "#sql-block"},
                    {"include": "#dbt-charts-property-keys"},
                    {"include": "#dbt-charts-enum-values"},
                    {"include": "#generic-key-value"},
                ]
            },
            "dbt-charts-top-level-keys": _top_level_keys_pattern(
                manifest.top_level_keys
            ),
            "dbt-charts-definition-names": {
                "comment": "Definition names at 2-space indent - use yellow/function color",
                "patterns": [
                    {
                        "match": "^(  )([a-zA-Z_][a-zA-Z0-9_-]*)(:)\\s*$",
                        "captures": {
                            "2": {"name": "entity.name.function.yaml"},
                            "3": {"name": "punctuation.separator.key-value.yaml"},
                        },
                    },
                    {
                        "match": "^(  )([a-zA-Z_][a-zA-Z0-9_-]*)(:)(?=\\s+\\S)",
                        "captures": {
                            "2": {"name": "entity.name.function.yaml"},
                            "3": {"name": "punctuation.separator.key-value.yaml"},
                        },
                    },
                ],
            },
            "dbt-charts-property-keys": {
                "comment": "Property keys at 4+ space indent - use light blue/variable color",
                "patterns": [
                    {
                        "match": "^(\\s{4,})([a-zA-Z_][a-zA-Z0-9_-]*)(:)",
                        "captures": {
                            "2": {"name": "variable.other.property.yaml"},
                            "3": {"name": "punctuation.separator.key-value.yaml"},
                        },
                    }
                ],
            },
            "dbt-charts-enum-values": _enum_values_patterns(
                manifest.enum_values_by_key
            ),
            "sql-block": _sql_block_pattern(manifest.sql_block_scalar_keys),
            "sql-content": {
                "comment": "SQL syntax - use purple/magenta keywords, cyan functions",
                "patterns": [
                    {
                        "name": "comment.line.double-dash.sql",
                        "match": "--.*$",
                    },
                    {
                        "name": "comment.block.sql",
                        "begin": "/\\*",
                        "end": "\\*/",
                    },
                    {
                        "name": "keyword.control.sql",
                        "match": (
                            "(?i)\\b(SELECT|INSERT|UPDATE|DELETE|MERGE|UPSERT|FROM|WHERE"
                            "|AND|OR|NOT|IN|EXISTS|BETWEEN|LIKE|ILIKE|IS|AS|ON|JOIN"
                            "|INNER|LEFT|RIGHT|FULL|OUTER|CROSS|NATURAL|USING"
                            "|GROUP\\s+BY|HAVING|ORDER\\s+BY|ASC|DESC|NULLS|FIRST|LAST"
                            "|LIMIT|OFFSET|FETCH|UNION|INTERSECT|EXCEPT|ALL|DISTINCT"
                            "|CASE|WHEN|THEN|ELSE|END|CAST|OVER|PARTITION\\s+BY|WINDOW"
                            "|ROWS|RANGE|PRECEDING|FOLLOWING|UNBOUNDED|CURRENT|ROW"
                            "|WITH|RECURSIVE|LATERAL|FILTER|WITHIN|GROUP|BY|ORDER"
                            "|PARTITION)\\b"
                        ),
                    },
                    {
                        "name": "storage.type.sql",
                        "match": (
                            "(?i)\\b(TABLE|VIEW|INDEX|SCHEMA|DATABASE|FUNCTION"
                            "|PROCEDURE|TRIGGER|CONSTRAINT|PRIMARY|FOREIGN|KEY"
                            "|REFERENCES|UNIQUE|CHECK|DEFAULT|CREATE|ALTER|DROP"
                            "|TRUNCATE|RENAME|NULL|TRUE|FALSE)\\b"
                        ),
                    },
                    {
                        "name": "support.function.sql",
                        "match": (
                            "(?i)\\b(COUNT|SUM|AVG|MIN|MAX|ARRAY_AGG|STRING_AGG"
                            "|LISTAGG|GROUP_CONCAT|ANY_VALUE|MEDIAN|PERCENTILE_CONT"
                            "|PERCENTILE_DISC|STDDEV|VARIANCE|COVAR_POP|COVAR_SAMP"
                            "|CORR|REGR_SLOPE|REGR_INTERCEPT|COALESCE|NULLIF|NVL"
                            "|IFNULL|IIF|GREATEST|LEAST|ABS|CEIL|CEILING|FLOOR|ROUND"
                            "|TRUNC|TRUNCATE|MOD|POWER|SQRT|EXP|LOG|LN|LOG10|SIGN"
                            "|RANDOM|RAND|LENGTH|LEN|CHAR_LENGTH|LOWER|UPPER|INITCAP"
                            "|TRIM|LTRIM|RTRIM|LPAD|RPAD|SUBSTR|SUBSTRING|REPLACE"
                            "|TRANSLATE|CONCAT|CONCAT_WS|SPLIT|SPLIT_PART|REVERSE"
                            "|REPEAT|SPACE|ASCII|CHR|CHAR|POSITION|STRPOS|INSTR"
                            "|LOCATE|REGEXP_REPLACE|REGEXP_EXTRACT|REGEXP_SUBSTR"
                            "|REGEXP_MATCH|DATE|TIME|TIMESTAMP|DATETIME|DATE_TRUNC"
                            "|DATE_PART|EXTRACT|YEAR|MONTH|DAY|HOUR|MINUTE|SECOND"
                            "|WEEK|QUARTER|DOW|DOY|EPOCH|NOW|CURRENT_DATE|CURRENT_TIME"
                            "|CURRENT_TIMESTAMP|GETDATE|SYSDATE|TODAY|DATEADD|DATE_ADD"
                            "|DATEDIFF|DATE_DIFF|TO_DATE|TO_CHAR|TO_NUMBER"
                            "|TO_TIMESTAMP|FORMAT|TRY_CAST|SAFE_CAST|PARSE_JSON"
                            "|JSON_EXTRACT|JSON_VALUE|JSON_QUERY|ARRAY|UNNEST"
                            "|GENERATE_SERIES|ROW_NUMBER|RANK|DENSE_RANK|NTILE|LAG"
                            "|LEAD|FIRST_VALUE|LAST_VALUE|NTH_VALUE|FIRST|LAST|LEFT"
                            "|RIGHT)\\b"
                        ),
                    },
                    {
                        "name": "constant.numeric.sql",
                        "match": "\\b\\d+(\\.\\d+)?([eE][+-]?\\d+)?\\b",
                    },
                    {
                        "name": "string.quoted.single.sql",
                        "begin": "'",
                        "end": "'",
                        "patterns": [
                            {
                                "name": "constant.character.escape.sql",
                                "match": "''",
                            }
                        ],
                    },
                    {
                        "name": "string.quoted.double.sql",
                        "begin": '"',
                        "end": '"',
                        "patterns": [
                            {
                                "name": "constant.character.escape.sql",
                                "match": '""',
                            }
                        ],
                    },
                    {
                        "name": "variable.other.column.sql",
                        "match": "\\b[a-zA-Z_][a-zA-Z0-9_]*\\b",
                    },
                    {
                        "name": "keyword.operator.sql",
                        "match": "<=|>=|<>|!=|<|>|=|\\+|-|\\*|/|%|\\|\\|",
                    },
                    {
                        "name": "punctuation.separator.sql",
                        "match": "[,.]",
                    },
                    {
                        "name": "meta.parens.sql",
                        "begin": "\\(",
                        "end": "\\)",
                        "patterns": [
                            {"include": "#jinja-template"},
                            {"include": "#sql-content"},
                        ],
                    },
                ],
            },
            "jinja-template": {
                "comment": "Jinja templates - bright orange/gold for visibility",
                "patterns": [
                    {
                        "name": "meta.embedded.expression.jinja",
                        "begin": "(\\{\\{-?)",
                        "beginCaptures": {
                            "1": {"name": "punctuation.section.embedded.begin.jinja"}
                        },
                        "end": "(-?\\}\\})",
                        "endCaptures": {
                            "1": {"name": "punctuation.section.embedded.end.jinja"}
                        },
                        "patterns": [{"include": "#jinja-expression"}],
                    },
                    {
                        "name": "meta.embedded.statement.jinja",
                        "begin": "(\\{%-?)",
                        "beginCaptures": {
                            "1": {"name": "punctuation.section.embedded.begin.jinja"}
                        },
                        "end": "(-?%\\})",
                        "endCaptures": {
                            "1": {"name": "punctuation.section.embedded.end.jinja"}
                        },
                        "patterns": [{"include": "#jinja-statement"}],
                    },
                    {
                        "name": "comment.block.jinja",
                        "begin": "\\{#",
                        "end": "#\\}",
                    },
                ],
            },
            "jinja-expression": {
                "patterns": [
                    {
                        "name": "entity.name.function.jinja",
                        "match": (
                            "\\b(filter|ref|source|var|env|config|this|metric"
                            "|dimension)\\b"
                        ),
                    },
                    {
                        "name": "keyword.control.jinja",
                        "match": "\\b(if|else|elif|and|or|not|in|is)\\b",
                    },
                    {
                        "name": "support.function.jinja",
                        "match": (
                            "\\b(abs|attr|batch|capitalize|center|default|dictsort"
                            "|escape|filesizeformat|first|float|forceescape|format"
                            "|groupby|indent|int|join|last|length|list|lower|map|max"
                            "|min|pprint|random|reject|rejectattr|replace|reverse|round"
                            "|safe|select|selectattr|slice|sort|string|striptags|sum"
                            "|title|trim|truncate|unique|upper|urlencode|urlize"
                            "|wordcount|wordwrap|xmlattr)\\b"
                        ),
                    },
                    {
                        "name": "variable.other.jinja",
                        "match": "\\b[a-zA-Z_][a-zA-Z0-9_]*\\b",
                    },
                    {
                        "name": "string.quoted.single.jinja",
                        "begin": "'",
                        "end": "'",
                        "patterns": [
                            {
                                "name": "constant.character.escape.jinja",
                                "match": "\\\\.",
                            }
                        ],
                    },
                    {
                        "name": "string.quoted.double.jinja",
                        "begin": '"',
                        "end": '"',
                        "patterns": [
                            {
                                "name": "constant.character.escape.jinja",
                                "match": "\\\\.",
                            }
                        ],
                    },
                    {
                        "name": "constant.numeric.jinja",
                        "match": "\\b\\d+(\\.\\d+)?\\b",
                    },
                    {
                        "name": "constant.language.jinja",
                        "match": "\\b(true|false|none|True|False|None)\\b",
                    },
                    {
                        "name": "keyword.operator.jinja",
                        "match": "[|~+\\-*/%]|==|!=|<=|>=|<|>",
                    },
                ]
            },
            "jinja-statement": {
                "patterns": [
                    {
                        "name": "keyword.control.jinja",
                        "match": (
                            "\\b(if|else|elif|endif|for|endfor|block|endblock"
                            "|extends|include|import|from|macro|endmacro|call"
                            "|endcall|filter|endfilter|set|endset|raw|endraw"
                            "|with|endwith|autoescape|endautoescape)\\b"
                        ),
                    },
                    {"include": "#jinja-expression"},
                ]
            },
            "generic-key-value": {
                "patterns": [
                    {
                        "match": "([a-zA-Z_][a-zA-Z0-9_-]*)(:)(?=\\s|$)",
                        "captures": {
                            "1": {"name": "entity.name.tag.yaml"},
                            "2": {"name": "punctuation.separator.key-value.yaml"},
                        },
                    },
                    {
                        "begin": "([a-zA-Z_][a-zA-Z0-9_-]*)(:)\\s+",
                        "beginCaptures": {
                            "1": {"name": "entity.name.tag.yaml"},
                            "2": {"name": "punctuation.separator.key-value.yaml"},
                        },
                        "end": "$",
                        "patterns": [{"include": "#scalar"}],
                    },
                ]
            },
            "block-sequence": {
                "patterns": [
                    {
                        "name": "punctuation.definition.block.sequence.item.yaml",
                        "match": "^\\s*-\\s+",
                    }
                ]
            },
            "flow-collection": {
                "patterns": [
                    {"include": "#flow-mapping"},
                    {"include": "#flow-sequence"},
                ]
            },
            "flow-mapping": {
                "name": "meta.flow-mapping.yaml",
                "begin": "\\{",
                "beginCaptures": {
                    "0": {"name": "punctuation.definition.mapping.begin.yaml"}
                },
                "end": "\\}",
                "endCaptures": {
                    "0": {"name": "punctuation.definition.mapping.end.yaml"}
                },
                "patterns": [
                    {"include": "#comment"},
                    {"include": "#generic-key-value"},
                    {"include": "#scalar"},
                    {"name": "punctuation.separator.mapping.yaml", "match": ","},
                ],
            },
            "flow-sequence": {
                "name": "meta.flow-sequence.yaml",
                "begin": "\\[",
                "beginCaptures": {
                    "0": {"name": "punctuation.definition.sequence.begin.yaml"}
                },
                "end": "\\]",
                "endCaptures": {
                    "0": {"name": "punctuation.definition.sequence.end.yaml"}
                },
                "patterns": [
                    {"include": "#comment"},
                    {"include": "#scalar"},
                    {"name": "punctuation.separator.sequence.yaml", "match": ","},
                ],
            },
            "scalar": {
                "patterns": [
                    {"include": "#string-quoted-double"},
                    {"include": "#string-quoted-single"},
                    {"include": "#null"},
                    {"include": "#boolean"},
                    {"include": "#number"},
                    {"include": "#anchor"},
                    {"include": "#alias"},
                    {"include": "#jinja-template"},
                    {"include": "#string-unquoted"},
                ]
            },
            "string-quoted-double": {
                "name": "string.quoted.double.yaml",
                "begin": '"',
                "beginCaptures": {
                    "0": {"name": "punctuation.definition.string.begin.yaml"}
                },
                "end": '"',
                "endCaptures": {
                    "0": {"name": "punctuation.definition.string.end.yaml"}
                },
                "patterns": [
                    {"include": "#jinja-template"},
                    {
                        "name": "constant.character.escape.yaml",
                        "match": '\\\\(["\\\\/bfnrt]|u[0-9a-fA-F]{4})',
                    },
                ],
            },
            "string-quoted-single": {
                "name": "string.quoted.single.yaml",
                "begin": "'",
                "beginCaptures": {
                    "0": {"name": "punctuation.definition.string.begin.yaml"}
                },
                "end": "'",
                "endCaptures": {
                    "0": {"name": "punctuation.definition.string.end.yaml"}
                },
                "patterns": [
                    {"include": "#jinja-template"},
                    {
                        "name": "constant.character.escape.yaml",
                        "match": "''",
                    },
                ],
            },
            "string-unquoted": {
                "name": "string.unquoted.yaml",
                "match": "[^\\s\\[\\]\\{\\},#&*!|>'\"%@`][^\\s\\[\\]\\{\\},#:]*",
            },
            "null": {
                "name": "constant.language.null.yaml",
                "match": "(?<=:\\s*)(null|Null|NULL|~)\\s*$",
            },
            "boolean": {
                "name": "constant.language.boolean.yaml",
                "match": "(?<=:\\s*)(true|True|TRUE|false|False|FALSE|yes|Yes|YES|no|No|NO)\\s*$",
            },
            "number": {
                "patterns": [
                    {
                        "name": "constant.numeric.yaml",
                        "match": "(?<=:\\s*)[-+]?\\d+(\\.\\d+)?([eE][+-]?\\d+)?\\s*$",
                    }
                ]
            },
            "anchor": {
                "name": "entity.name.type.anchor.yaml",
                "match": "&[a-zA-Z0-9_-]+",
            },
            "alias": {
                "name": "variable.other.alias.yaml",
                "match": "\\*[a-zA-Z0-9_-]+",
            },
        },
    }
